export const authActions = {
  AUTH_LOGIN: "AUTH_LOGIN",
  RESET_STATE: "RESET_STATE",
  AUTH_LOGOUT: "AUTH_LOGOUT",
};
export const superAdminActions = {
  SUPER_ADMIN_CHANGE_PASSWORD: "SUPER_ADMIN_CHANGE_PASSWORD",
  SUPER_ADMIN_FORGOT_PASSWORD: "SUPER_ADMIN_FORGOT_PASSWORD",
  SUPER_ADMIN_SEND_OTP: "SUPER_ADMIN_SEND_OTP",
  SUPER_ADMIN_ADD_SOCIETY: "SUPER_ADMIN_ADD_SOCIETY",
  GET_ALL_SOCIETY: "GET_ALL_SOCIETY",
  GET_ALL_DESIGNATION: "GET_ALL_DESIGNATION",
  SUPER_ADMIN_VIEW_SOCIETY: "SUPER_ADMIN_VIEW_SOCIETY",
  SUPER_ADMIN_VIEW_DESIGNATION: "SUPER_ADMIN_VIEW_DESIGNATION",
  VIEW_DESIGNATION: "VIEW_DESIGNATION",
};
export const societyAdminActions = {
  SOCIETY_ADMIN_CHANGE_PASSWORD: "SOCIETY_ADMIN_CHANGE_PASSWORD",
  SOCIETY_ADMIN_FORGOT_PASSWORD: "SOCIETY_ADMIN_FORGOT_PASSWORD",
  GET_ALL_NOTICE: "GET_ALL_NOTICE",
  GET_SELECTED_NOTICE: "GET_SELECTED_NOTICE",
  GET_ALL_PHONE_DIRECTORY: "GET_ALL_PHONE_DIRECTORY",
  GET_SELECTED_PHONE_DIRECTORY: "GET_SELECTED_PHONE_DIRECTORY",
  GET_ALL_COMPLAINT: "GET_ALL_COMPLAINT",
  GET_SELECTED_COMPLAINT: "GET_SELECTED_COMPLAINT",
};
export const residentialUserActions = {
  RESIDENT_SIGNUP: "RESIDENT_SIGNUP",
  RESIDENT_DELETE: "RESIDENT_DELETE",
  RESIDENT_UPDATE: "RESIDENT_UPDATE",
  FETCH_ALL_RESIDENT: "FETCH_ALL_RESIDENT",
  FETCH_SELECTED_RESIDENT: "FETCH_SELECTED_RESIDENT",
  RESIDENT_FORGOT_PASSWORD: "RESIDENT_FORGOT_PASSWORD",
  RESIDENT_CHANGE_PASSWORD: "RESIDENT_CHANGE_PASSWORD",
  RESIDENT_SEND_OTP: "RESIDENT_SEND_OTP",
};
